### ISSUE TITLE
Add azuread_user_detail and azuread_group_detail

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-mod-azure-insights#26]
**Is your feature request related to a problem? Please describe.**

- [ ] Link Azure Active Directory Group Age Report to `azuread_group_detaii`
- [ ] Azure Active Directory User Age Report to `azuread_user_detail`
 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rajlearner17** [comment]
Released
