### ISSUE TITLE
"Invoking Azure CLI failed with the following error: (SQLSTATE HV000)"

### ISSUE THREAD

**Issue by anandvamsi** [turbot/steampipe-mod-azure-insights#98]
Team-

I'm running steampipe version v0.19.4 with azure and azuread plugin 
I see i'm able to pull data from few of the azure tables where as  few not; Im getting an error saying "Invoking Azure CLI failed with the following error: (SQLSTATE HV000)"
I have observed same error in "azure dashboard insights" as well as while generating CIS1.5 benchmark report.

Please find my reference aws.spc and azuread.spc in the config dir
>> azure.spc
connection "azure_sub_1" {
  plugin          = "azure"
  tenant_id       = "f31f568b-1232323wdwdrefdsf"
  subscription_id = "1264246d4-bdfdfdfdfd6a2"
  client_id       = "8fe6259a7dfdfdfdf"
  client_secret   = "6c338Q~D-af9WUB3pgwdfewst4wtt2_Hami"
}
>> azuread.spc
connection "azure_sub_11" {
  plugin          = "azuread"
 tenant_id       = "f31f568b-1232323wdwdrefdsf"
  client_id       = "8fe6259a7dfdfdfdf"
   client_secret   = "6c338Q~D-af9WUB3pgwdfewst4wtt2_Hami"
}

Help is appreciated 

**Describe the bug**

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by cbruno10** [comment]
Hi @anandvamsi , I believe we're already talking in a Steampipe Slack thread, but based on the latest tests, can you please  run through the following debugging steps:
- Can you please share the Steampipe CLI version (`steampipe -v`) and plugin versions (`steampipe plugin list`)?
- Can you please share the output when you run `steampipe check control.cis_v130_9_9`?
- Can you please share the results of running the query `select * from azure_subscription` (do not include `azure_sub_1` in the query)?
- Do any other benchmarks run? For instance, `steampipe check benchmark.nist_sp_800_53_rev_5_au_6_5`?
- Do you have any Steampipe or Azure env vars set (`env | grep -E 'AZURE|STEAMPIPE'`) ?

Thanks!

**Comment by anandvamsi** [comment]
Hi Team-

Please find the output
>>
#select * from azure_subscription; :: Not getting results
Invoking Azure CLI failed with the following error: ERROR: Please run 'az
login' to setup account

#steampipe -v
Steampipe v0.19.4

steampipe plugin list
+------------------------------------------------+---------+-------------------+
| Installed Plugin                               | Version | Connections
    |
+------------------------------------------------+---------+-------------------+
| ***@***.***     | 0.99.0  | aws
    |
| ***@***.***   | 0.40.1  |
azure_sub_1,azure |
| ***@***.*** | 0.9.0   | azure_sub_11
   |
| ***@***.***     | 0.35.0  | gcp,gcp_cloud
    |
| ***@***.*** | 0.4.0   | grafana
    |
| ***@***.***     | 0.21.0  | oci_new,oci
    |
+------------------------------------------------+---------+-------------------+


steampipe check control.cis_v130_9_9
+ 9.9 Ensure that 'HTTP Version' is the latest, if used to run the web app
.............................................................. 1 / 1
[==========]

  ERROR: Invoking Azure CLI failed with the following error: ERROR: Please
run 'az login' to setup account.
 (SQLSTATE HV000)

#env | grep -E 'AZURE|STEAMPIPE'
***@***.*** ~]$


steampipe check benchmark.nist_sp_800_53_rev_5_au_6_5
>>All of them same error

ERROR: Invoking Azure CLI failed with the following error: ERROR: Please
run 'az login' to setup account.
 (SQLSTATE HV000)

**Comment by cbruno10** [comment]
@anandvamsi As per the Slack thread, it seems this issue is resolved as you mentioned there was a conflict with the info in your `~/.steampipe/config/default.spc`. If you're still having issues though, feel free to reopen!
